### ISSUE TITLE
Text stopped scrolling automatically

### ISSUE THREAD

**Issue by r-valyar** [elizeuangelo/fvtt-module-narrator-tools#29]
After the last update the text stopped auto-scrolling.  If the paragraph is bigger than than those 9-10 line on the screen it is cut. Only the chat message is not abriged.

**Comment by elizeuangelo** [comment]
Fixed!

**Comment by r-valyar** [comment]
Hi @elizeuangelo , It seems that the text is still not scrolling. I am not sure if this is because the journal entry is not properly prepared. This is example I try to display in the screen, and it is basically cut after the second paragraph:

```
Distances shift. Paths between places warp.
As if this pale, lightless world possessed a will and bitter life. Its mercy curdled to wrath over a too-long age.

Who are you? The grave robber with silver glittering between cracked fingernails? The mystic who would bend the world’s miserable heart away from its inevitable end?

Most likely, it makes little difference. No one has seen the sun in years. The old care more for sacrifice and god-offerings than their bawling spawn. Doomsayers are proved right time and again and embraced by hidden powers. Maybe it’s best to surrender—to trust your own instinct and skill rather than the whim of the dice? Before all is drowned in welcome silence. Life locked and failing in a DARK FORT.
```

**Comment by elizeuangelo** [comment]
My bad, should be solved now.

**Comment by r-valyar** [comment]
Yes, it is perfect :) Thank you a lot for the prompt fix.
